### PR TITLE
Add GetManager method

### PR DESCRIPTION
**Pull request by gbitten**
GetManager method returns the current managers of a Gui.

User case: 
By retrieving the current managers, I was able to encapsulate some behavior in the widget as a method and call this method if the widget is "running". In the bellow example, there is a method to update the widget content, and a go rotine that updates the widget content periodically.

```golang
type Widget struct {}

func (w *Widget) Layout(g *gocui.Gui) (err error) {
	// Create views and keybindings
}

func (w *Widget) Update(g *gocui.Gui) {
	// Update widget content
}

func Update(g *gocui.Gui) {
	for {
		g.Execute(func(g *gocui.Gui) error {
			managers := g.GetManager()
			for _, m := range managers {
				switch w := m.(type) {
				case (*Widget):
					w.Update(g)
				}
			}
			return nil
		})
		time.Sleep(1 * time.Second)
	}
}

func main() {
	g := gocui.NewGui()
	defer g.Close()
	w := new(Widget)
	g.SetManager(w)
	go Update(g)
	g.MainLoop()
}
```

### CODE REVIEW

**Comment by jroimartin** [comment]
Why not passing the widget instance to `Update()` instead of getting it from managers?

For example, in `widgets.go`:
* Binding the action: https://github.com/jroimartin/gocui/blob/master/_examples/widgets.go#L127-L128
* Updating the widget: https://github.com/jroimartin/gocui/blob/master/_examples/widgets.go#L156-L174

**Comment by jroimartin** [comment]
Small example: https://gist.github.com/jroimartin/b78c4c33c67a289dc028dd7d562e1f6e

Does it covers your use case?

**Comment by gbitten** [comment]
There are others don't details of my app that I was not explicit. It has 4 widgets until now (there be more in the future) and the users can turn them on or off any time they want. To do so, I am resetting the managers when user chooses to open or to close a widget.

I could control which widgets are open in my app and pass them to my update rotine, but it seems to me a more elegant solution to get this information from the GUI.

**Comment by jroimartin** [comment]
The thing is that the `Manager` interface, as you know, is defined as follows:

```go
type Manager interface {
	Layout(*Gui) error
}
```

and `Layout()` is a function that is intended to be called internally from the main loop. So, my main concern about adding this getter is that it would return something (`[]Manager`) that is not really useful, from the user side, without performing a type assertion.

From my point of view, this can be a bit confusing and is the user who should take care of the manager instances externally.

**Comment by gbitten** [comment]
I understand you point. Thanks anyway.

**Comment by jroimartin** [comment]
Thank you for your understanding! :)

**Pull request closed without merging**
