### PR TITLE
Made it configurable how to handle cr/lf in the input data.

### PR DESCRIPTION
**Pull request by zond**

### CODE REVIEW

**Comment by jroimartin** [comment]
First of all, sorry for the BIG delay. Could you please check commit 17f7615184739fbeb00ec824f6f894d22558e92e to see if solves this issue? :)

**Comment by zond** [comment]
It looks like it would solve my problem, even if I gave up when I realized that another and much harder problem remained: ANSI control codes :O

I ended up building a distributed app where one terminal runs the input window and several others run output windows that just print everything on stdout and letting the terminal handle all rendering...

**Comment by jroimartin** [comment]
Why would you use ANSI control codes if you control the output? Of course, if you are not generating this output, that would be a problem. Anyway you could filter/replace them, couldn't you?

BTW I'm planning to give color support to gocui in the next days, but probably using some human-friendly syntax (issue #9).

**Comment by zond** [comment]
> Why would you use ANSI control codes if you control the output? Of
course, if you are not generating this output, that would be a problem.

I was building a MUD client, and it was important to render the incoming
data exactly as the server software intended.

> Anyway you could filter/replace them, couldn't you?

I built a MUD client like this before, in Ruby, and that time around I used
ncurses and intercepted all incoming ANSI escape codes and replaced them
with ncurses commands.

That was easily the least interesting and most work intensive part of that
client, so I'd rather not do it again ;)

> BTW I'm planning to give color support to gocui in the next days, but
probably using some human-friendly syntax (issue #9).

Cool, but consider rendering ANSI commands properly as well, it might come
in handy :)

**Comment by jroimartin** [comment]
I'll take it into account, thanks!

**Pull request closed without merging**
